version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:80"
    depends_on: 
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "PalpatinewasaJ4d1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"